numName = {
    1: "Basileus Romanos of Roman Empire",          # Father & Uncle
    2: "Emperess Nikarete of Roman Empire",         # Mother, Aunt, and Sister-in-law

    3: "Emperor Romanos VI of Roman Empire",        # POV
    4: "Basilissa Alexeia II of Roman Empire",      # Sister, Cousin, and Sister-in-law         (m. 23 Sep 1253 -death  - 16 Nov 1298)
    8: "Basilissa Sophia of Roman Empire",          # Daughter-wife, Niece, and Sister-in-law   (m. 24 Nov 1298 -present-            )

    5: "Princess Nikarete II of Roman Empire",      # Daughter, Niece, and Sister-in-law
    6: "Princess Theodosia of Roman Empire",        # Daughter, Niece, and Sister-in-law
    7: "Despot Romanos IV of Egypt",                # Son, Nephew, and Brother-in-law
    9: "Prince Chrysogonos of Roman Empire",        # Son, Nephew, and Brother-in-law
    
    10: "Princess Sophia of Roman Empire",          # Daughter, Granddaughter, and Sister-in-law 
    11: "Prince Romanos of Roman Empire",           # Son, Grandson, and Brother-in-law 
    12: "Princess Alexeia II of Roman Empire",      # Daughter, Granddaughter, and Sister-in-law 

    ### Lover or Concubine ###
    13: "Duchess Antonia of Bavaria",               # Concubine
    14: "Prince Georgios of Roman Empire",          # Son and Brother-in-law

    15: "Marina Domingez Barrientos",               # Lover
    16: "Prince Alexios Romanosesz of Roman Empire" # Son and Brother-in-law
}

nameDNA = {
    "Basileus Romanos of Roman Empire"          : "zdPzxItvjHAqr77IAGwAewB3AHcAfQF/AHwAdwGLAHsBgwGDAYwBggGAAboAdgGMAYkBpgHEAbEBiwGGAYwBgQGlAYUAfABZAGYAXAB+AH4BrQGrAYkBiQGIAYQAdABzAYwBiQGCAYIAfABkAYEAdgGyAYwAWwGIAYABgABuAGwAUQBRAZUBlQB1AHAABwEBAQwBIAERAREBGwEbABwAHAJ7AF8BCgA5AWcAHgG8Ae4BHAB1AF4AJQEmAS0AnABiAG0BVQBtAQgADgFpAUoBVQE5ABwAKwArAAwBaAAYABgAdAB0ACkAKQEXAH4BHAABABkAGQAdAbkAegAHARkBGQEgASABJQEAAQoAeQEpAUwAZAEhAV0AEwBgARIBEwETAUwAAgENAQ0AEAAPAAUABQHFAWwEmgOZALAAsADZAMQAfAC3AwIC3QEJAQkBDAAOAM0AzQD0APQAKAJSAE0ChwDoAOgCAAIABJoEmgF8AXwChgF+CAAIAALWCZ0ATQKoCokKiQHnAecAaAG6AbcApQHbAawAeAB4AAAAAAEmASY=",
    "Emperess Nikarete of Roman Empire"         : "88Rw+Yxwi26+yByyAHsAbAB3AH8AfQB9AGUAZQGLAHsBgwGDAYwBjAGAAboBjAB2AYkBpgHEAbEBhgBtAYEBgQGlAYUAWQB8AGYAXAB+AH4BrQGtAYkBkQGIAYQAfAB0AYwAVQGCAYIAfABkAHYAdgGyAYwAWwGIAYAAcwBuAEoAHgBRAZUBlQBwAHUBAQEBAQwBDAERAREBGwEbABwAHABJAF8BCgA5AWcALwHuAbwBLQB1AF4AXgEmASYAnABiAVUAbQEIAUIADgAOAUoBVQE5ABwAKwArAWgBaAAYACMAdAB0ACkAKQEXAH4BHAABAAwAKgAdALYABwEKAA0BGQEgASABAAElAQoBDQEpAUwAZABkAj8AEwBgARIBEwETAAIBTAENAQ0ADwAPAAUBAgHFAWwDmQSaAQAAsADEANkAfAB8AQkDAgEJAAEADgEMAM0AzQD0APQAKAAoAE0ChwDoAOgCAAIABH8EmgF8AXwDcwF+CAAIAALWCZ0ATQF7CokKiQHnAecBugBoAYwBtwHiAdsApwCnAAAAAAGbAZs=",

    "Emperor Romanos VI of Roman Empire"        : "88TN04tvi2++yCqvAHsAbAB3AH8AfQB9AHwAZQGLAHsBgwGDAYIBjAGAAYABjAB2AYkBiQHEAbEBiwGGAYwBgQGlAaUAfABZAGYAZgB+AH4BqwGtAYkBiQGIAYQAdAB0AYwBiQGCAYIAfABkAHYBgQGMAbIBiABbAYABgABuAG4AHgBRAZUBlQB1AHUBAQAHASABDAERAREBGwEbABwAHAJ7AEkAOQEKAWcBZwG8Ae4AdQEcAF4AXgEmASYAnACcAG0BVQEIAUIADgAOAVUBSgAcABwAKwArAAwBaAAYABgAdAB0ACkAKQEXAH4BHAABABkAKgAdAbkAegAHARkBGQEgASABAAEAAQoBCgEpASkAZABkABMAEwBgAGABEwETAUwAAgENAQ0AEAAPAAUBAgFsAcUDmQSaALABAADEAMQAfAB8At0BCQEJAQkBDAAOAM0AzQD0APQAKAAoAE0ChwDoAOgCAAIABJoEfwF8AXwChgNzCAAIAAmdAtYATQBNCokKiQHnAecAaABoAYwApQHiAdsAGgAaAAAAAAGsAaw=",
    "Basilissa Alexeia II of Roman Empire"      : "zdNw+Ytui24qrxyyAGwAewB/AHcAfQB9AHcAZQB7AYsBgwGDAYIBjAG6AYABjAB2AYkBpgHEAcQAbQGLAYwBgQGlAaUAfABZAGYAZgB+AH4BrQGtAYkBiQGIAYgAfAB0AFUBjAGCAYIAfABkAHYAdgGyAYwAWwBbAYABgABuAG4AHgBRAZUBlQB1AHUBAQAHAQwBDAERAREBGwEbABwAHABJAnsAOQEKAWcBZwHuAbwBLQEcAF4AXgEmASYAnACcAVUBVQFCAG0ADgAOAUoBVQAcATkAKwArAWgADAAYABgAdAB0ACkAKQEXARcBHAEcAAwAGQAdAB0ABwB6AA0BGQEgASABJQEAAQoBCgFMAUwAZABkAj8BXQESAGABEwETAAIBTAENAQ0ADwAQAAUABQHFAcUEmgOZALABAADEAMQAfAB8At0DAgEJAQkADgEMAM0AzQD0APQAKAJSAE0ATQDoAOgCAAIABJoEmgF8AXwChgF+CAAIAAmdAtYATQBNCokKiQHnAecBugBoAYwBtwHiAdsAbQBtAAAAAAEyATI=",
    "Basilissa Sophia of Roman Empire"          : "88TN04tui26+yCqvAHsAewB3AH8AfQB9AHwAZQB7AHsBgwGDAYIBggGAAboAdgGMAYkBiQGxAcQBhgBtAYEBjAGlAaUAWQB8AGYAZgB+AH4BrQGtAYkBiQGIAYgAdAB0AFUBjAGCAYIAfABkAHYAdgGMAbIAWwGIAYABgABuAG4AHgAeAZUBlQB1AHUABwEBAQwBIAERAREBGwEbABwAHABJAnsAOQA5AWcBZwHuAbwAdQEtAF4AXgEmASYAnACcAVUAbQFCAQgADgAOAVUBSgAcABwAKwArAWgBaAAYABgAdAB0ACkAKQEXARcBHAEcAAwAKgAdAB0ABwAHARkADQEgASABJQEAAQoBCgEpAUwAZABkABMBXQESAGABEwETAAIAAgENAQ0ADwAQAAUABQHFAWwDmQOZALAAsADEAMQAfAB8At0C3QEJAQkBDAAOAM0AzQD0APQAKAJSAE0ATQDoAOgCAAIABH8EmgF8AXwChgKGCAAIAAmdCZ0ATQBNCokKiQHnAecAaAG6AKUBjAHiAeIAfwB/AAAAAAEOAQ4=",

    "Princess Nikarete II of Roman Empire"      : "zdPN04tui24qryqvAHsAbAB/AHcAfQB9AHwAdwGLAYsBgwGDAYIBggGAAboAdgGMAYkBiQHEAcQBiwGLAYEBjAGlAaUAfAB8AGYAZgB+AH4BrQGrAYkBiQGIAYgAdAB0AYwAVQGCAYIAfAB8AHYAdgGMAbIAWwBbAYABgABuAG4AUQAeAZUBlQB1AHUABwEBAQwBDAERAREBGwEbABwAHAJ7AEkAOQEKAWcBZwG8Ae4BHAB1AF4AXgEmASYAnACcAVUBVQFCAQgADgAOAVUBVQAcABwAKwArAAwADAAYABgAdAB0ACkAKQEXARcBHAEcAAwAGQAdAB0ABwAHARkBGQEgASABAAElAQoBCgEpAUwAZABkABMCPwBgAGABEwETAAIAAgENAQ0ADwAQAAUABQHFAcUEmgOZALAAsADEAMQAfAB8At0C3QEJAQkADgAOAM0AzQD0APQAKAAoAE0ATQDoAOgCAAIABJoEmgF8AXwChgKGCAAIAAmdAtYATQBNCokKiQHnAecAaAG6AbcBjAHiAeIAiACIAAAAAAEgASA=",
    "Princess Theodosia of Roman Empire"        : "zdPzxItui24qr77IAHsAewB3AH8AfQB9AHwAdwB7AYsBgwGDAYIBjAG6AYABjAB2AYkBiQHEAcQBiwBtAYwBjAGlAaUAfAB8AGYAZgB+AH4BrQGrAYkBiQGIAYgAfAB0AFUBjAGCAYIAfAB8AYEAdgGMAbIBiABbAYABgABuAG4AHgAeAZUBlQB1AHUBAQEBAQwBIAERAREBGwEbABwAHABJAEkAOQA5AWcBZwG8AbwBLQB1AF4AXgEmASYAnACcAVUBVQFCAQgADgAOAUoBVQAcABwAKwArAWgBaAAYABgAdAB0ACkAKQB+ARcBHAEcACoADAAdAB0ABwB6ARkADQEgASABJQEAAQoBCgFMASkAZABkABMCPwBgARIBEwETAUwAAgENAQ0ADwAQAAUABQFsAcUDmQSaALAAsADEAMQAfAB8At0C3QEJAQkADgAOAM0AzQD0APQAKAAoAE0ATQDoAOgCAAIABJoEmgF8AXwChgF+CAAIAAmdAtYATQBNCokKiQHnAecBugBoAYwBjAHiAeIAKgAqAAAAAAHwAfA=",
    "Despot Romanos IV of Egypt"                : "88TN04tui26+yCqvAGwAewB3AHcAfQB9AHcAfAB7AHsBgwGDAYIBjAGAAboBjAB2AYkBiQHEAcQAbQGLAYwBjAGlAaUAfAB8AGYAZgB+AH4BqwGtAYkBiQGIAYgAfAB0AYwAVQGCAYIAfAB8AYEAdgGyAYwAWwBbAYABgABuAG4AHgAeAZUBlQB1AHUBAQAHASABDAERAREBGwEbABwAHAJ7AEkAOQA5AWcBZwHuAbwBLQB1AF4AXgEmASYAnACcAVUBVQEIAUIADgAOAUoBVQAcABwAKwArAWgADAAYABgAdAB0ACkAKQEXARcBHAEcAAwAKgAdAbkAegB6ARkADQEgASABJQEAAQoBCgEpAUwAZABkABMCPwESAGABEwETAUwAAgENAQ0ADwAQAAUABQHFAWwEmgOZAQAAsADEAMQAfAB8At0DAgEJAQkBDAAOAM0AzQD0APQAKAAoAE0ChwDoAOgCAAIABH8EmgF8AXwChgKGCAAIAAmdCZ0ATQBNCokKiQHnAecAaABoAbcBjAHiAeIAigCKAAAAAAGnAac=",
    "Prince Chrysogonos of Roman Empire"        : "88Rw+Ytui26+yByyAHsAewB3AH8AfQB9AHcAfAGLAYsBgwGDAYIBjAGAAYAAdgGMAaYBiQHEAcQBhgBtAYwBgQGlAaUAfABZAGYAZgB+AH4BrQGtAYkBiQGIAYgAdAB8AFUBjAGCAYIAfAB8AHYAdgGyAbIAWwGIAYABgABuAG4AHgBRAZUBlQB1AHUABwEBASABDAERAREBGwEbABwAHAJ7AEkAOQA5AWcBZwG8Ae4BLQB1AF4AXgEmASYAnACcAG0BVQFCAQgADgAOAUoBSgAcABwAKwArAAwBaAAYABgAdAB0ACkAKQEXARcBHAEcABkADAAdAB0ABwB6ARkADQEgASABAAEAAQoBCgFMASkAZABkABMBXQBgAGABEwETAUwBTAENAQ0ADwAQAAUABQFsAcUDmQSaALAAsADEAMQAfAB8At0C3QEJAQkADgEMAM0AzQD0APQAKAAoAE0ATQDoAOgCAAIABJoEmgF8AXwChgKGCAAIAALWCZ0ATQBNCokKiQHnAecBugBoAYwApQHiAeIAJgAmAAAAAAFjAWM=",
    "Princess Sophia of Roman Empire"           : "zdPzxItui24qr77IAHsAewB3AHcAfQB9AHwAfAB7AYsBgwGDAYIBggGAAboAdgGMAYkBiQGxAcQBhgGLAYEBjAGlAaUAWQB8AGYAZgB+AH4BrQGtAYkBiQGIAYgAdAB0AFUBjAGCAYIAZAB8AHYBgQGMAYwAWwGIAYABgABuAG4AHgAeAZUBlQB1AHUBAQEBASABIAERAREBGwEbABwAHABJAEkAOQEKAWcBZwG8Ae4AdQB1AF4AXgEmASYAnACcAG0AbQFCAQgADgAOAUoBVQAcABwAKwArAWgADAAYABgAdAB0ACkAKQEXARcBHAABAAwAKgAdAB0ABwB6AA0BGQEgASABJQEAAQoBCgEpASkAZABkABMAEwESAGABEwETAAIBTAENAQ0ADwAQAAUABQFsAWwEmgOZALAAsADEAMQAfAB8At0C3QEJAQkBDAEMAM0AzQD0APQAKAAoAE0ATQDoAOgCAAIABJoEfwF8AXwChgKGCAAIAAmdCZ0ATQBNCokKiQHnAecAaABoAYwApQHbAeIA0wDTAAAAAAF2AXY=",
    "Prince Romanos of Roman Empire"            : "88TzxItui26+yL7IAHsAewB3AHcAfQB9AHwAfAB7AHsBgwGDAYwBggG6AYAAdgGMAYkBiQHEAcQBhgGLAYwBgQGlAaUAWQBZAGYAZgB+AH4BrQGrAYkBiQGIAYgAdAB0AYwAVQGCAYIAZABkAHYAdgGMAbIAWwBbAYABgABuAG4AHgBRAZUBlQB1AHUBAQEBASABIAERAREBGwEbABwAHAJ7AEkAOQA5AWcBZwHuAbwAdQB1AF4AXgEmASYAnACcAVUAbQEIAUIADgAOAVUBVQAcABwAKwArAAwBaAAYABgAdAB0ACkAKQEXARcBHAEcAAwAGQG5AB0ABwAHAA0BGQEgASABAAElAQoBCgEpAUwAZABkABMBXQESAGABEwETAAIBTAENAQ0ADwAPAAUABQHFAWwEmgOZALAAsADEAMQAfAB8At0C3QEJAQkBDAEMAM0AzQD0APQAKAJSAE0ATQDoAOgCAAIABJoEfwF8AXwDcwKGCAAIAAmdCZ0ATQBNCokKiQHnAecBugBoAKUBjAHbAeIAaABoAAAAAAG1AbU=",
    "Princess Alexeia II of Roman Empire"       : "zdPzxItui24qr77IAGwAewB3AHcAfQB9AHwAfAGLAHsBgwGDAYIBggGAAboAdgGMAYkBiQHEAcQAbQGGAYwBjAGlAaUAWQB8AGYAZgB+AH4BqwGtAYkBiQGIAYgAdAB0AFUBjAGCAYIAfABkAHYAdgGMAYwAWwGIAYABgABuAG4AUQAeAZUBlQB1AHUBAQAHASABIAERAREBGwEbABwAHABJAnsAOQA5AWcBZwG8Ae4AdQB1AF4AXgEmASYAnACcAVUAbQEIAUIADgAOAUoBVQAcABwAKwArAWgADAAYABgAdAB0ACkAKQB+ARcBHAEcAAwAGQAdAB0ABwB6ARkADQEgASABJQEAAQoBCgEpASkAZABkABMBXQBgARIBEwETAAIAAgENAQ0ADwAQAAUBAgHFAcUDmQSaALAAsADEAMQAfAB8At0C3QEJAQkBDAEMAM0AzQD0APQAKAAoAocATQDoAOgCAAIABJoEfwF8AXwChgKGCAAIAAmdAtYATQBNCokKiQHnAecAaABoAKUBjAHiAeIAZgBmAAAAAAHTAdM=",

    "Duchess Antonia of Bavaria"                : "trQO5YdfiWKenxK3AFUATgB9AHkBlgB1AHwAegB8AYsBjABwAYYBhQGSAYsBhgB0AagBpAGsAacBkwGEAHUBjAGIAaUBfwGGAZsBkwB+AHQB2AGXAYkAfwGEAYsAdAB7AGYB3gB6AHQAfAF/AHQAdgF/AbIAWwByAHwAfQB8AGgBgwGuAHABhAGNAG4AJQAZAB4AAgACAQkBMgAHAGYAxgJ1AC4BHgArAR0ABAGqAboBUgBQATIBGAFDACwBMgBAAAsADAEZAAEATgBSAVoBdQB4AI0ASAAZAWUBDgEWAA4AdABaAAcAqgEgARcAMAAYAGMAGQFjACEAFQE4ATkAGgAmACEAJAEPAXgACwALAWQAXAAWAR8AFQESASABDQEzAAIBNQAgASoADwAWARYADwBrAaEDmQEFAAQAsAEKAAMAngBoAAAEBQAPAAgBCACfAKQA3AAvAPsCUgLYAJ8ABgDoAocCAAIABJoCmwGKAXwBmQKCCBYJAAmdAhwA+AJMBZsH6gHSA6UBfwCGAYwArAG/AdsAdwB3AAAAAAEtAS0=",
    "Prince Georgios of Roman Empire"           : "trTzxIloiGWen77IAFUAewB9AH8AfQGWAHoAfAB8AHsBjAGDAYIBhgGLAYABhgB2AYkBqAGnAcQBhgGEAYwAdQGlAaUBfwBZAGYBmwB+AH4BqwHYAYkBiQGEAYQAewB0AGYBiQGCAHoAZAB8AHYAdAF/AYwAWwBbAYAAfQBuAHwAHgGuAHABlQB1AY0AJQEBASAAHgACAREBGwEyABwAxgAuAnsAOQEeAWcABAGqAe4AdQBQARgAXgEmAUMBMgCcAAsAbQEZAQgADgBOAVUBWgAcAI0ASAArAAwBZQEWABgAdAB0ACkABwEXARcBHAAwAGMAGQAdACEAegAVATkBGQAmASABDwEAAXgBCgALASkAZABcABMBHwESAGABMwETAUwAAgENACAAEAAPAAUBFgFsAaEDmQEFAAQAsAADAMQAfABoAAABCQAIAQkAnwEMAM0A3AD7APQAKALYAAYATQDoAOgCAAIABJoEfwF8AYoChgGZCQAIAAmdAhwATQD4CokH6gHnAdIAaAF/AYwApQHbAb8A6wDrAAAAAAHxAfE=",
    
    "Marina Domingez Barrientos"                : "vMZ86JBrlmwMqT/FAY4BoQB+AHMAfgB9AX8AfgB8AHwBhgB+AHsBhwGTAYEAfgB/AY0AbAGZAaEAcwB2AFcB0wB+AH0BlgBpAGEBrQB5AH4AfABQADcBhQB4AYcBiQGeAX8AbgGEAHIBhwB7AYUAeAB4AZoBhgB1AHkAeQBXAGoADgF/AZAAdAGUAGwBBgAIAH8BDQAMAA8BDgABAB4AOQEbAiYABQENAG4ANwHEAfkAAwBwASEBIwGxARsBBwCjAA4BbgFvABkAfAAOAVIAAgAaAMcAEgCAAR8BAQEnAF8ADAFPAAwACAFkAA8BAgASAHcAeAARAbQBdQFUAQwBUQEMABMBJwAOABgBEwAPASIAywAiAAQBEAAzAREBWAAwAV8ACAFPAQUBKwBDAQ8BJwARARkDUgCkARQAEwECAAAAnwB5AggBmgIKAhAAQwBYAOkAFACLAPEDGQFZAEUCqwArAaECAAIABFkETwF/AZwBcwOKARwIAAhbCHoC6wO/AtsD3APZAq0ArgKLAZUBnQGZAY4AJAAkAAAAAAHcAdw=",
    "Prince Alexios Romanosesz of Roman Empire" : "vMbzxI1tjWwMqb7IAHsBjgB3AHMAfQB+AX8AZQGLAHwAfgGDAYIAewGTAYABjAB+AYkBjQHEAZkAdgGGAFcBgQB+AaUBlgBZAGEAZgB+AH4BqwBQADcBiQGIAHgAdAGJAX8BjAGEAYIAfAGHAYEBhQGMAHgBhgGIAHkBgABuAGoADgBRAZABlQGUAHUBAQAIASABDQAMAREBGwEOAB4AHAEbAnsAOQAFAWcAbgG8AcQAAwB1ASEAXgEmAbEAnAEHAA4AbQFvAQgADgB8AAIBVQDHABwAgAArAAwBHwEnABgADAB0AAgAKQB+AWQAAQECABkAdwAdABEBdQB6ARkBDAEMASAADgEAABgBCgEpAA8AywBkABMBEABgADMBEwAwAUwBXwENAU8BKwAQAQIBDwARAWwDmQCkALAAEwDEAAAAfACfAt0CCAEJAgoAQwAOAOkAzQD0APEDGQAoAocARQArAOgCAAIABFkEfwF/AXwBcwKGARwIAALWCHoATQLrAtsKiQHnA9kCiwBoAZUBjAHiAZkAEgASAAAAAAHUAdQ=",
}
##
##  AAAAAAAAAAAAAAAAAH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/AH8AAAAAAAAAAAAAAAA=
##
def povOption():
    for i in range(1,17):
        print(f"{i} - {numName[i]}")
    print("\nPlease select a character to see DNA similarity...\n")
    user = int(input("> "))
    user = numName[user]
    return user

def genDNAlist():
    dnaList = []
    for i in range(1,17):
        cur = nameDNA[numName[i]]
        dnaList.append(cur)
    return dnaList

def compare(character):
    povDNA = nameDNA[character]
    povDNAlen = len(povDNA)
    dnaList = genDNAlist()
    score = []
    for x in range(len(dnaList)):
        comDNA = dnaList[x]
        turn = 0
        for y in range(povDNAlen):
            if comDNA[y] == povDNA[y]:
                turn += 1
        score.append(round(((turn/povDNAlen)*100), 2))
    return score

def board(score):
    for i in range(1,17):
        print(f"{numName[i]} \t- {score[i-1]}%")
print(3841876 - 3839740)
#board(compare(povOption()))